### ISSUE TITLE
[New feature request] Allow Guzzle options

### ISSUE THREAD

**Issue by dugwood** [inetprocess/sugarcrm-apiwrapper#5]
We've got a use case where some requests may block our processes for too long. Can you allow passing Guzzle options in the request?

Here:
http://docs.guzzlephp.org/en/stable/request-options.html#connect-timeout
=> must be implemented in the Guzzle `request` method

But here:
https://github.com/inetprocess/sugarcrm-apiwrapper/blob/master/src/BaseRequest.php#L299
=> all options are sent to `body` and `headers` (if we ignore the special case for file upload)

Another option would be to allow this at the Guzzle creation:
https://github.com/inetprocess/sugarcrm-apiwrapper/blob/master/src/BaseRequest.php#L79
=> here we can add some options. For example instead of `$verify = false` we could have `['verify' => false, 'cookies' => true]` as a default, which would allow changing all options.

Or just add 2 options there, for `connect_timeout` and `timeout`.

Thanks!

**Comment by FremontRaphael** [comment]
Hi Yvan,

We made some changes in order to allow users to override the options passed to the GuzzleClient.
We kept old functionning for backward compatibility.

So if you need to use your own options you should call the BaseRequest with parameters :
`('baseUrl', 'v11', true, ['verify' => true, 'someOption' => 1, 'otherOption' => 'test'])`
Please note that you will need to specify all options to use inside the array and still send `verify` parameter before.

If that's not answering your needs you can still use it like before while we work on another solution.

Best regards,

**Comment by dugwood** [comment]
@FremontRaphael it's okay for me, just have a look at my comment here: https://github.com/inetprocess/sugarcrm-apiwrapper/commit/d6968795adb18c4d3849ff51ab1b53a7216c4ceb#commitcomment-55602108

Please advise me when 1.0.9 is released on packagist. Thanks!
